CREATE TABLE IF NOT EXISTS saloon_collections (town_id VARCHAR(36) PRIMARY KEY, collected_at BIGINT NOT NULL, FOREIGN KEY(town_id) REFERENCES towns(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS town_guests (town_id VARCHAR(36) PRIMARY KEY, name VARCHAR(160) NOT NULL, visited_at BIGINT NOT NULL, FOREIGN KEY(town_id) REFERENCES towns(id) ON DELETE CASCADE);
DROP TABLE IF EXISTS town_visits;
INSERT INTO schema_versions(version) VALUES (12);
